### ISSUE TITLE
Nancy Pelosi tracker

### ISSUE THREAD

**Issue by TimKoornstra** [StephanAkkerman/fintwit-bot#661]
### Request reason
Pelosi

### Additional context
Money

### Describe the solution you'd like
Nancy channel

### Additional context
https://www.quiverquant.com/congresstrading/politician/Nancy%20Pelosi-P000197 like this

**Comment by StephanAkkerman** [comment]
Related to #632

**Comment by TimKoornstra** [comment]
Duplicate of #632
