### ISSUE TITLE
Empty Databases

### ISSUE THREAD

**Issue by dingslebumsle** [StephanAkkerman/fintwit-bot#665]
Hello, great work. However, I have two questions. Every time I restart, the FinTwit bot searches for the databases and says it can't find any. Although they are there. If I delete them, it creates them again. But the databases remain empty and the error comes again on restart.

> 28/10/2024 11:19:07 - ERROR - No portfolio.db found, returning empty db
> 28/10/2024 11:19:07 - ERROR - No assets.db found, returning empty db
> 28/10/2024 11:19:07 - ERROR - No tweets.db found, returning empty db
> 28/10/2024 11:19:07 - ERROR - No reddit_ids.db found, returning empty db
> 28/10/2024 11:19:07 - ERROR - No ideas_ids.db found, returning empty db
> 28/10/2024 11:19:07 - ERROR - No classified_tickers.db found, returning empty db
> 28/10/2024 11:19:07 - ERROR - No options.db found, returning empty db
> 28/10/2024 11:19:07 - INFO - Loading cogs from folder: commands
> 28/10/2024 11:19:07 - INFO - Loading: help.py
> 28/10/2024 11:19:07 - INFO - Loading: sentiment.py
> 28/10/2024 11:19:07 - INFO - Loading: portfolio.py
> 28/10/2024 11:19:08 - ERROR - No portfolio.db found, returning empty db

The second question is, is it possible to change the behaviour so that the bot deletes the old messages (on Discord) when it sends new messages to Discord? Is this a bot setting or a problem with my Discord server?

Thank you very much

**Comment by StephanAkkerman** [comment]
Hi, the error of empty databases happens if the .db files are not found.
You mention that they do exist, in which directory is that?
What messages would you like to be deleted, some of them are already automatically deleted for certain channels, this can be done by adding a few python lines in the cog that handles that channel. I might be able to add this to the config.

**Comment by dingslebumsle** [comment]
Hello, thanks for the answer. The databases are in the data folder, but they are all 0 bytes in size.

![datafolder](https://github.com/user-attachments/assets/b25d9ae2-013d-4e13-892e-ecf2d90cf540)

‘What messages would you like to be deleted’ I don't want them to be deleted, unless there is a deeper meaning that I haven't realised yet.

**Comment by StephanAkkerman** [comment]
> The second question is, is it possible to change the behaviour so that the bot deletes the old messages (on Discord) when it sends new messages to Discord? Is this a bot setting or a problem with my Discord server?
What exactly do you mean by this then? Can you give an example of the behavior you would like to see?

> The databases are in the data folder, but they are all 0 bytes in size.
This will take some time to be filled, just let it run for a bit and it should start to fill up

**Comment by dingslebumsle** [comment]
For example, this one, the old one is always deleted and only the new one remains. That's what I meant by that. With stocktwits, for example, the older messages also remain.

![new](https://github.com/user-attachments/assets/2c9426dc-8842-452a-a8b7-e8bbf1fc0033)

Ok, but with every bot restart no databases are found. Hence the question. They are presumably always recreated. The Bot runs like last week, but this databases are still empty.

This is from the logfile.

> 28/10/2024 11:19:07 - ERROR - No portfolio.db found, returning empty db
> 28/10/2024 11:19:07 - ERROR - No assets.db found, returning empty db
> 28/10/2024 11:19:07 - ERROR - No tweets.db found, returning empty db
> 28/10/2024 11:19:07 - ERROR - No reddit_ids.db found, returning empty db
> 28/10/2024 11:19:07 - ERROR - No ideas_ids.db found, returning empty db
> 28/10/2024 11:19:07 - ERROR - No classified_tickers.db found, returning empty db
> 28/10/2024 11:19:07 - ERROR - No options.db found, returning empty db
> 28/10/2024 11:19:07 - INFO - Loading cogs from folder: commands
> 28/10/2024 11:19:07 - INFO - Loading: help.py
> 28/10/2024 11:19:07 - INFO - Loading: sentiment.py
> 28/10/2024 11:19:07 - INFO - Loading: portfolio.py
> 28/10/2024 11:19:08 - ERROR - No portfolio.db found, returning empty db

**Comment by StephanAkkerman** [comment]
> For example, this one, the old one is always deleted and only the new one remains. That's what I meant by that. With stocktwits, for example, the older messages also remain.

So would you like it to be configurable? I can add something to the config.yaml for that.

> Ok, but with every bot restart no databases are found. Hence the question. They are presumably always recreated. The Bot runs like last week, but this databases are still empty.

That is strange, on what OS are you running it? Are you running it using `python src/main.py`?

**Comment by dingslebumsle** [comment]
> So would you like it to be configurable? I can add something to the config.yaml for that.

Hello, no, I don't want you to work extra because of me, I just thought it was a misbehaviour of the bot.
 
> That is strange, on what OS are you running it? Are you running it using `python src/main.py`?

The bot runs on Linux Mint Ubuntu. Yes, now I have also discovered my mistake. I had mistakenly called it directly in the src directory. With the call `python src/main.py` the databases are now also filled directly. Sorry and many thanks for the effort.

**Comment by StephanAkkerman** [comment]
Great, glad it was solved!
