### ISSUE TITLE
Missing tls-client-arm64.so

### ISSUE THREAD

**Issue by butterjesus1911** [StephanAkkerman/fintwit-bot#685]
Hi, building this on a raspberry pi 5, debian 11, tried using python 3.9 and 3.12. After configuring and renaming example.env, running python3 src/main.py produces the following error output:
![issue](https://github.com/user-attachments/assets/646eb855-4d34-451f-9d03-959758152854)

Any workaround?
Thanks!

**Comment by StephanAkkerman** [comment]
Yes I had a similar problem, you need to follow the instructions here: https://github.com/FlorianREGAZ/Python-Tls-Client/issues/111
Maybe I can add this file to the repo or to the readme so that it becomes easier to fix.

**Comment by butterjesus1911** [comment]
That fixed it. Thanks!
